plugins {
    alias(libs.plugins.androidLibrary)
}

android {
    namespace 'io.chthonic.weather.domain.presentationapi'
    compileSdk versions.targetSdk

    defaultConfig {
        minSdk versions.minSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}

kotlin {
    jvmToolchain(libs.versions.jvmTarget.get().toInteger())
}

dependencies {
    implementation libs.androidx.core
    implementation project(path: ':common')

    // paging
    implementation libs.paging.runtime

    // logging
    implementation libs.timber

    // testing
    testImplementation libs.junit
}