plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace 'io.chthonic.weather.data.common'
    compileSdk versions.targetSdk

    defaultConfig {
        minSdk versions.minSdk
        targetSdk versions.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
}

kotlin {
    jvmToolchain(libs.versions.jvmTarget.get().toInteger())
}

dependencies {
    api project(path: ':common')
    implementation libs.androidx.core
    implementation project(path: ':domain:dataapi')

    // coroutines, flow
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // json
    implementation libs.ktorClient.serialization
    implementation libs.ktorClient.serializationJson

    // di
    implementation libs.hilt.android
    ksp libs.hilt.android.compiler

    // net / rest
    implementation libs.ktorClient.contentNegotiation
    implementation libs.ktorClient.android
    implementation libs.ktorClient.logging
    implementation libs.ktorClient.okhttp


    // logging
    api libs.timber

    // testing
    testImplementation libs.junit
}