plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace 'io.chthonic.weather.feature.cityforecast'
    compileSdk versions.targetSdk

    defaultConfig {
        minSdk versions.minSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

kotlin {
    jvmToolchain(libs.versions.jvmTarget.get().toInteger())
}

dependencies {
    implementation libs.androidx.core
    implementation project(path: ':common')
    implementation project(path: ':ui:common')
    implementation project(path: ':domain:presentationapi')

    // di
    implementation libs.hilt.android
    ksp libs.hilt.android.compiler
    implementation libs.hilt.navigation.compose

    // compose
    implementation platform(libs.compose.bom)
    implementation libs.compose
    implementation libs.compose.material3
    implementation libs.compose.icons.extended
    implementation libs.compose.tooling.preview
    debugImplementation libs.compose.tooling
    implementation libs.compose.lifecycle.runtime

    // immutable
    implementation libs.kotlinx.immutables

    // navigation
    implementation libs.navigation
    implementation libs.navigation.compose

    // viewModel
    implementation libs.viewmodel
    implementation libs.viewmodel.compose
    implementation libs.viewmodel.runtime

    // coroutines, flow
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // logging
    implementation libs.timber

    // testing
    testImplementation libs.junit
}